GET http://127.0.0.1:3000/workday/John

###

GET http://127.0.0.1:3000/workday/John/1635926320059

###

POST http://127.0.0.1:3000/workday/John
Content-Type: application/json

{
    "userId": "John",
    "dayId": "10/22/2021",
    "checkIn": 1634984837125
}

###

PATCH http://127.0.0.1:3000/workday/John/1635926320059
Content-Type: application/json

{
    "userId": "John",
    "checkIn": 1634984837125,
    "checkOut": 1634912816820,
    "pause": [{
        "start": 1634912816820,
        "end": 1634984837125
    }]
}

###

GET http://127.0.0.1:3000/user

###

POST http://127.0.0.1:3000/user
Content-Type: application/json

{
    "userId": "John",
    "pw": "helloo"
}

###

PATCH http://127.0.0.1:3000/user
Content-Type: application/json

{
    "userId": "John",
    "pw": "helloo"
}